name: CI and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: yourusername/yourimage:latest

  deploy:
    name: Deploy to Server via SSH
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: SSH into server and deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          REPO_URL: ${{ github.repositoryUrl }}
          PROJECT_DIR: /home/user/prod
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          first_ssh: |
            echo "Cloning repository..."
            rm -rf ${{ env.PROJECT_DIR }}
            git clone ${{ env.REPO_URL }} ${{ env.PROJECT_DIR }}
            cd ${{ env.PROJECT_DIR }}
            echo "Running docker compose down..."
            docker compose down -f docker-compose-prod.yml
            echo "Running docker compose up -d..."
            docker compose -f docker-compose-prod.yml up -d