name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:14
          ports:
            - 5432:5432
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: fider_test
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    env:
      COMMITHASH: ${{ github.sha }}
      VERSION: ${{ github.ref_name }}
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/fider_test?sslmode=disable
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Go dependencies
        run: go mod tidy

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6

      - name: Install godotenv-cli
        run: go install github.com/joho/godotenv/cmd/godotenv@latest
      
      - name: Lint server
        run: make lint-server

      - name: Lint UI
        run: make lint-ui

      - name: Build
        run: make build

      - name: Run unit tests (server)
        run: make test-server

      - name: Run unit tests (UI)
        run: make test-ui
       
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: wushie/fider:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max